import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.bundle.min';
import './fonts/Poppins-Regular.ttf';
import './fonts/Poppins-SemiBold.ttf';
import './fonts/Poppins-SemiBoldItalic.ttf';
import './fonts/Poppins-Thin.ttf';
import './fonts/Poppins-ThinItalic.ttf';
import './fonts/Poppins-Italic.ttf';
import './fonts/Poppins-Black.ttf';
import './fonts/Poppins-BlackItalic.ttf';
import './fonts/Poppins-Bold.ttf';
import './fonts/Poppins-BoldItalic.ttf';
import './fonts/Poppins-ExtraBold.ttf';
import './fonts/Poppins-ExtraBoldItalic.ttf';
import './fonts/Poppins-ExtraLight.ttf';
import './fonts/Poppins-ExtraLightItalic.ttf';
import './fonts/Poppins-Light.ttf';
import './fonts/Poppins-LightItalic.ttf';
import './fonts/Poppins-Medium.ttf';
import './fonts/Poppins-MediumItalic.ttf';
import './fonts/Bank-Gothic-Regular.ttf';

ReactDOM.render(<App />, document.getElementById('root'));
